#!/usr/bin/env ruby
#^syntax detection
 
site 'http://community.opscode.com/api/v1'
 
cookbook 'apt'
cookbook 'git', 
  git: 'https://github.com/fnichol/chef-git.git'
cookbook 'build-essential'
cookbook 'rvm', 
  git: 'git://github.com/fnichol/chef-rvm.git', ref: 'v0.9.0'